Repository BC-MAY-21-ROR/proyecto-final-proyecto-final-aug-21-team-01, pull requests merged in 2021-12, with the labels that each got.

#61 navbar layout refactoring
  app/controllers/home_controller.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/partials/_nav_private.html.erb
  app/views/layouts/partials/_nav_public.html.erb
  app/views/layouts/partials/_user_options.html.erb
Labels: mentor review required, ready for review, review required

#60 Add styles to signup and signin views
  app/assets/images/Mobile-Logo.svg
  app/assets/images/Mobile-Logo.svg:Zone.Identifier
  app/assets/images/logo-white.svg
  app/assets/images/logo-white.svg:Zone.Identifier
  app/assets/images/logo_white_large.svg
  app/assets/images/logo_white_large.svg:Zone.Identifier
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  config/initializers/simple_form.rb
  config/locales/simple_form.en.yml
  lib/templates/erb/scaffold/_form.html.erb
  stylesheets/abstracts/mixins.scss
  stylesheets/application.scss
  stylesheets/application/layout.scss
  stylesheets/application/objects/buttons.scss
  stylesheets/application/objects/inputs.scss
  stylesheets/application/objects/labels.scss
  stylesheets/application/responsive/mobile.scss
  stylesheets/application/typography.scss
Labels: mentor review required, ready for review, review required

#63 Add individual and groups contribution budget
  app/models/category.rb
  app/models/group.rb
  app/models/participant.rb
  app/models/user.rb
  app/views/groups/index.html.erb
  app/views/groups/show.html.erb
  lib/tasks/auto_annotate_models.rake
Labels: mentor review required, ready for review, review required

#67 Add styles on Navbar
  Gemfile
  Gemfile.lock
  app/assets/images/icons/hamburger-icon.svg
  app/assets/images/icons/logo-header.svg
  app/helpers/application_helper.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/home/partials/_hero.html.erb
  app/views/layouts/partials/_nav_private.html.erb
  app/views/layouts/partials/_nav_public.html.erb
  app/views/layouts/partials/_user_options.html.erb
  stylesheets/abstracts/_variables.scss
  stylesheets/application.scss
  stylesheets/base/_base.scss
  stylesheets/views/_navbar.scss
  stylesheets/views/_newLogin.scss
  stylesheets/views/_userOptions.scss
Labels: ready for review

#68 Add user plan type restrictions
  app/controllers/groups_controller.rb
  app/helpers/application_helper.rb
  app/javascript/controllers/alert_controller.js
  app/javascript/controllers/index.js
  app/javascript/packs/application.js
  app/models/group.rb
  app/models/user.rb
  app/views/groups/_form.html.erb
  app/views/groups/_group.html.erb
  app/views/groups/_participating_user_fields.erb
  app/views/groups/edit.html.erb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/groups/show.html.erb
  app/views/layouts/partials/_messages.html.erb
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#70 Add layout and styles in hero section
  app/assets/images/icons/family-and-friends.svg
  app/views/home/index.html.erb
  app/views/home/partials/_hero.html.erb
  stylesheets/abstracts/_mixins.scss
  stylesheets/abstracts/mixins.scss
  stylesheets/application.scss
  stylesheets/views/_hero.scss
  stylesheets/views/_navbar.scss
Labels: ready for review

#73 Adding about us layout with styles
  app/assets/images/icons/group-friends.svg
  app/assets/images/icons/group-friends.svg:Zone.Identifier
  app/views/home/index.html.erb
  app/views/home/partials/_about.html.erb
  stylesheets/abstracts/_mixins.scss
  stylesheets/abstracts/_variables.scss
  stylesheets/application.scss
  stylesheets/views/_about.scss
  stylesheets/views/_hero.scss
Labels: mentor review required, ready for review, review required

#75 Fix Individual Contribution for the amount in the group
  app/models/group.rb
  spec/factories/groups.rb
  spec/models/group_spec.rb
Labels: mentor review required, ready for review, review required

#77 Creates layout and add design the benefits section
  app/assets/images/icons/benefits-image.svg
  app/assets/images/icons/groups-logo.svg
  app/assets/images/icons/secure-logo.svg
  app/assets/images/icons/service-logo.svg
  app/views/home/index.html.erb
  app/views/home/partials/_benefits.html.erb
  app/views/layouts/partials/_user_options.html.erb
  stylesheets/application.scss
  stylesheets/views/_about.scss
  stylesheets/views/_benefits.scss
  stylesheets/views/_infobar.scss
Labels: mentor review required, ready for review

#84 Hot fix to home page
  stylesheets/base/_base.scss
  stylesheets/views/_benefits.scss
  stylesheets/views/_hero.scss
  stylesheets/views/_infobar.scss
Labels: ready for review

#87 Layout and design of pricing plan section
  app/assets/images/icons/free-icon.svg
  app/assets/images/icons/free-mobile.svg
  app/assets/images/icons/premium-icon.svg
  app/assets/images/icons/premium-mobile.svg
  app/views/home/index.html.erb
  app/views/home/partials/_pricing.html.erb
  app/views/home/partials/_separator.html.erb
  stylesheets/abstracts/_variables.scss
  stylesheets/application.scss
  stylesheets/base/_base.scss
  stylesheets/views/_pricing.scss
Labels: ready for review

#91 Add stripe implementation to users
  .env.example
  Gemfile
  Gemfile.lock
  app/assets/images/icons/user.svg
  app/controllers/application_controller.rb
  app/controllers/groups_controller.rb
  app/controllers/preferences_controller.rb
  app/controllers/stripe_controller.rb
  app/controllers/webhooks_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/models/group.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.erb
  app/views/layouts/dashboard.html.erb
  app/views/layouts/partials/_nav_private.html.erb
  app/views/layouts/partials/_user_account.html.erb
  app/views/preferences/plan.html.erb
  app/views/stripe/upgrade.js.erb
  config/environments/development.rb
  config/initializers/stripe.rb
  config/routes.rb
  config/webpack/environment.js
  db/migrate/20211206192659_add_fields_to_users.rb
  db/schema.rb
  package.json
  spec/models/user_spec.rb
  yarn.lock
Labels: mentor review required, ready for review, review required

#93 hotfix to solve specific things
  app/views/layouts/partials/_nav_private.html.erb
  app/views/layouts/partials/_nav_public.html.erb
  app/views/layouts/partials/_user_account.html.erb
  stylesheets/views/_navbar.scss
Labels: ready for review

#94 add footer layout and style to landing view
  app/assets/images/Mobile-Logo.svg:Zone.Identifier
  app/assets/images/icons/facebook.svg
  app/assets/images/icons/group-friends.svg:Zone.Identifier
  app/assets/images/icons/instagram.svg
  app/assets/images/icons/logo-mobile.svg
  app/assets/images/icons/twitter.svg
  app/assets/images/logo-white.svg:Zone.Identifier
  app/assets/images/logo_white_large.svg:Zone.Identifier
  app/views/layouts/application.html.erb
  app/views/layouts/partials/_footer.html.erb
  stylesheets/application.scss
  stylesheets/views/_footer.scss
Labels: mentor review required, ready for review, review required

#96 Hotfix to login and register styles
  app/helpers/application_helper.rb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  stylesheets/abstracts/_variables.scss
  stylesheets/application.scss
  stylesheets/base/_form.scss
  stylesheets/views/_login.scss
  stylesheets/views/_navbar.scss
  stylesheets/views/_newLogin.scss
  stylesheets/views/_register.scss
Labels: mentor review required, ready for review, review required

#98 Change price in premium plan
  app/assets/images/kangaroo-favicon.png
  app/views/home/partials/_pricing.html.erb
Labels: ready for review

#100 Groups route in the private navbar
  app/views/layouts/partials/_nav_private.html.erb
  app/views/layouts/partials/_user_account.html.erb
  app/views/layouts/partials/_user_options.html.erb
  stylesheets/application.scss
  stylesheets/views/_userAccount.scss
Labels: mentor review required, ready for review, review required

#110 Add email integration
  .env.example
  Gemfile
  Gemfile.lock
  app/mailers/application_mailer.rb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/layouts/application.html.erb
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/devise.rb
Labels: mentor review required, ready for review, review required

#111 Modify landing page
  stylesheets/views/_about.scss
  stylesheets/views/_infobar.scss
Labels: ready for review

#113 Hotfix groups card mobile
  app/views/groups/_form.html.erb
  app/views/groups/_group.html.erb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/groups/show.html.erb
Labels: mentor review required, ready for review, review required
