Repository BC-MAY-21-ROR/proyecto-final-proyecto-final-aug-21-team-01, pull requests merged in 2021-11, with the labels that each got.

#22 Add postgres integration
  .env.example
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
Labels: mentor review required, ready for review, review required

#23 Webpacker and Bootstrap configuration
  Gemfile.lock
  app/javascript/css/styles.scss
  app/javascript/packs/application.js
  app/views/layouts/application.html.erb
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required

#26 Add root home page with controller
  app/controllers/home_controller.rb
  app/views/home/index.html.erb
  config/routes.rb
  spec/requests/home_spec.rb
  spec/views/home/index.html.erb_spec.rb
Labels: mentor review required, ready for review, review required

#27 Add Devise to user model for authentication
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/layouts/application.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20211112233346_devise_create_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: mentor review required, ready for review, review required

#28 Add Group Model
  app/models/group.rb
  db/migrate/20211117225213_create_groups.rb
  db/schema.rb
  spec/factories/groups.rb
  spec/models/group_spec.rb
Labels: mentor review required, ready for review, review required

#32 Add views for user routes
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
Labels: mentor review required, ready for review, review required

#33 Adding Design Mockups
  mockups/Desktop/DESKTOP-CARD.png
  mockups/Desktop/DESKTOP-DETAILS-GROUP.png
  mockups/Desktop/DESKTOP-FORM-GROUPS.png
  mockups/Desktop/DESKTOP-FORM-LOGIN.png
  mockups/Desktop/DESKTOP-FORM-REGISTER.png
  mockups/Desktop/DESKTOP-HOME.png
  mockups/Desktop/PAGE-INIT-ACTIVE-DESKTOP.png
  mockups/Desktop/PAGE-INIT-DESKTOP.png
  mockups/Mobile/MOBILE-CARD.png
  mockups/Mobile/MOBILE-DETAILS-GROUP.png
  mockups/Mobile/MOBILE-FORM-GRUPS.png
  mockups/Mobile/MOBILE-FORM-LOGIN.png
  mockups/Mobile/MOBILE-FORM-REGISTER.png
  mockups/Mobile/MOBILE-HOME-ACTIVE.png
  mockups/Mobile/MOBILE-HOME.png
  mockups/Mobile/PAGE-INIT-ACTIVE-MOBILE.png
  mockups/Mobile/PAGE-INIT-MOBILE.png
Labels: mentor review required, ready for review, review required

#30 Add Group Controller
  Gemfile
  Gemfile.lock
  app/controllers/groups_controller.rb
  app/models/group.rb
  app/models/user.rb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/schema.rb
  spec/controllers/groups_spec.rb
  spec/factories/groups.rb
  spec/factories/users.rb
  spec/models/group_spec.rb
  spec/models/user_spec.rb
  spec/requests/groups_spec.rb
Labels: mentor review required, ready for review, review required

#38 Add Category Model
  app/models/category.rb
  db/migrate/20211123002429_create_categories.rb
  db/schema.rb
  spec/models/category_spec.rb
Labels: mentor review required, ready for review, review required

#37 Create intermediate table, for groups and users.
  app/models/group.rb
  app/models/user.rb
  db/migrate/20211122235709_create_join_table.rb
  db/schema.rb
  spec/models/group_spec.rb
  spec/models/user_spec.rb
Labels: mentor review required, ready for review, review required

#36 Add references for users in Group model
  app/models/group.rb
  app/models/user.rb
  db/migrate/20211122224559_add_user_to_groups.rb
  db/schema.rb
  spec/models/group_spec.rb
  spec/models/user_spec.rb
Labels: mentor review required, ready for review

#45 Configuration test helper for applyng devise sessions
  spec/rails_helper.rb
Labels: review required

#43 Add necessary gems.
  Gemfile
  Gemfile.lock
Labels: mentor review required, ready for review, review required

#46 Fix Groups and User Associations
  app/controllers/groups_controller.rb
  app/models/category.rb
  app/models/group.rb
  app/models/participant.rb
  app/models/user.rb
  app/views/groups/show.html.erb
  db/migrate/20211124002334_create_participants.rb
  db/migrate/20211124004749_add_owner_to_group.rb
  db/migrate/20211124005527_drop_join_table_users_groups.rb
  db/migrate/20211124162238_remove_group_from_categories.rb
  db/migrate/20211124162501_add_category_to_groups.rb
  db/migrate/20211124164851_remove_user_references_from_groups.rb
  db/schema.rb
  spec/controllers/groups_spec.rb
  spec/factories/categories.rb
  spec/factories/groups.rb
  spec/factories/participants.rb
  spec/models/category_spec.rb
  spec/models/group_spec.rb
  spec/models/participant_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/groups_spec.rb
Labels: mentor review required, ready for review, review required

#47 Creates views for groups
  app/controllers/groups_controller.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/models/participant.rb
  app/views/devise/shared/_links.html.erb
  app/views/groups/_form.html.erb
  app/views/groups/_participating_user_fields.erb
  app/views/groups/edit.html.erb
  app/views/groups/index.html.erb
  app/views/groups/new.html.erb
  app/views/groups/show.html.erb
  app/views/layouts/application.html.erb
  config/webpack/environment.js
  db/seeds.rb
  package.json
  spec/controllers/groups_spec.rb
  yarn.lock
Labels: mentor review required, ready for review, review required

#49 Fix cocoon javascript dependency
  config/webpack/environment.js
Labels: mentor review required, ready for review, review required

#51 Fix Group Controller New Method
  app/controllers/groups_controller.rb
Labels: mentor review required, ready for review, review required

#53 Add authorization gem
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/groups_controller.rb
  app/models/ability.rb
  app/models/group.rb
  app/views/groups/index.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/partials/_messages.html.erb
  app/views/layouts/partials/_nav.html.erb
Labels: mentor review required, ready for review, review required

#58 navbar layout
  app/controllers/home_controller.rb
  app/javascript/packs/application.js
  app/views/home/index.html.erb
  app/views/home/partials/_nav.html.erb
  package.json
  yarn.lock
Labels: mentor review required, ready for review, review required
